name: deploy

on:
  pull_request:
    branches: 
      - dev
      - main
jobs:
  build_deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: npm install, build
      run: |
        npm install
        npm run build
      env:
        CI: true

    - name: gh-pages for Github Action
      uses: Cecilapp/GitHub-Pages-deploy@2.0.1
